#!/bin/csh

set lib_files = ""

set tb_files = "ClockGenerator.sv Tester.sv Testbench.sv"

set src_files = \
"../../../rtl/CommonDefinitions.v \
 ../../../rtl/Synchronizer.v \
 ../../../rtl/Peripherals/Handshaker.v"


alias openwv 'nWave -ssf Handshaker.fsdb -sswr Handshaker.rc'

alias startvd 'verdi -sv ${lib_files} ${src_files} ${tb_files} -ssf Handshaker.fsdb -sswr Handshaker.rc' 

vcs -full64 -sverilog -R -nc -debug_pp -LDFLAGS -rdynamic -P ${VERDI_HOME}/share/PLI/VCS/LINUX64/novas.tab ${VERDI_HOME}/share/PLI/VCS/LINUX64/pli.a +define+FSDB_DUMP -timescale=1ns/1ps ${lib_files} ${src_files} ${tb_files}
