#!/bin/csh

set lib_files = "../../altera_mf.v"
set tb_files = "../ClockGenerator.sv Tester.sv ../Testbench.sv"

set src_files = \
"../../../rtl/IP/Alt_EP4CE_DataMem_16KB.v \
 ../../../rtl/IP/Alt_EP4CE_InstrMem_4KB.v \
 ../../../rtl/IP/Alt_EP4CE_SysPLL.v \
 ../../../rtl/CommonDefinitions.v \
 ../../../rtl/AddressAdder.v \
 ../../../rtl/AddressInc.v \
 ../../../rtl/ArithmeticLogicUnit.v \
 ../../../rtl/BranchExceptionUnit.v \
 ../../../rtl/DataMemory.v \
 ../../../rtl/InstructionDecoder.v \
 ../../../rtl/InstructionMemory.v \
 ../../../rtl/InstructionRegister.v \
 ../../../rtl/RegisterEn.v \
 ../../../rtl/RegisterRstEn.v \
 ../../../rtl/RegisterFile.v \
 ../../../rtl/ResetSynchronizer.v \
 ../../../rtl/Synchronizer.v \
 ../../../rtl/CoreInterruptUnit.v \
 ../../../rtl/SystemPLL.v \
 ../../../rtl/Kabeta.v \
 ../../../rtl/Peripherals/Handshaker.v \
 ../../../rtl/Peripherals/IO_AddressTable.sv \
 ../../../rtl/Peripherals/IO_AccessItf.sv \
 ../../../rtl/Peripherals/IO_Interface.sv \
 ../../../rtl/Peripherals/ReadOnlyRegister.sv \
 ../../../rtl/Peripherals/ExtInterruptCtrl.sv \
 ../../../rtl/Peripherals/KabIO.sv \
 ../../../rtl/SystemChip.v"


alias openwv 'nWave -ssf SystemChip.fsdb -sswr SystemChip.rc'

alias startvd 'verdi -sv ${lib_files} ${src_files} ${tb_files} -ssf SystemChip.fsdb -sswr SystemChip.rc' 

vcs -full64 -sverilog -R -nc -debug_pp -LDFLAGS -rdynamic -P ${VERDI_HOME}/share/PLI/VCS/LINUX64/novas.tab ${VERDI_HOME}/share/PLI/VCS/LINUX64/pli.a +define+FSDB_DUMP ${lib_files} ${src_files} ${tb_files}
